"""
Master Data Templates Service — Section 10 V9

Generates downloadable Excel workbooks containing master data for a client.
Two flavors:
  1. BLANK template — empty workbook with headers + 1 sample row per sheet,
                      for fresh data entry (then upload via existing endpoints).
  2. EXPORT-CURRENT — populated with the client's existing data (directors,
                      shareholders, policies, custom CoA, signing details).

Workbook sheets:
  - README          (instructions, sheet index)
  - Client Master   (company info, auditor)
  - Directors       (name, DIN, designation, is_kmp, signs_financials)
  - Shareholders    (name, shares CY/PY, promoter flag, etc.)
  - Custom CoA      (custom codes for this client)
  - Policies        (accounting policies)
  - Signing Block   (project-level — only used for export-current of a project)
"""
from io import BytesIO
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from sqlalchemy.orm import Session

from app.models.client import Client, Director, ClientShareholder, CustomCoACode, ClientPolicy


# ----- Styling helpers -----

_HEADER_FONT = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
_HEADER_FILL = PatternFill(start_color="1F2A44", end_color="1F2A44", fill_type="solid")
_TITLE_FONT = Font(name="Calibri", size=14, bold=True, color="1F2A44")
_SUB_FONT = Font(name="Calibri", size=10, italic=True, color="666666")
_BORDER = Border(
    left=Side(style="thin", color="CCCCCC"),
    right=Side(style="thin", color="CCCCCC"),
    top=Side(style="thin", color="CCCCCC"),
    bottom=Side(style="thin", color="CCCCCC"),
)


def _style_header(cell):
    cell.font = _HEADER_FONT
    cell.fill = _HEADER_FILL
    cell.alignment = Alignment(horizontal="center", vertical="center")
    cell.border = _BORDER


def _style_body(cell):
    cell.font = Font(name="Calibri", size=10)
    cell.border = _BORDER
    cell.alignment = Alignment(vertical="center")


def _add_title(ws, title, subtitle=""):
    ws.cell(row=1, column=1, value=title).font = _TITLE_FONT
    if subtitle:
        ws.cell(row=2, column=1, value=subtitle).font = _SUB_FONT


def _write_headers(ws, headers, row=4):
    for col_idx, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col_idx, value=h)
        _style_header(cell)


def _write_rows(ws, rows, start_row=5):
    for r_idx, row_data in enumerate(rows, start=start_row):
        for c_idx, value in enumerate(row_data, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=value)
            _style_body(cell)


def _autosize(ws, min_width=12, max_width=42):
    for col_letter in [c.column_letter for c in ws[1]]:
        max_len = 0
        for cell in ws[col_letter]:
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = max(min_width, min(max_len + 3, max_width))


# ----- Sheet builders -----

def _build_readme(wb, client_name, mode):
    ws = wb.active
    ws.title = "README"
    _add_title(ws, f"Master Data Template — {client_name}",
               subtitle=f"Mode: {mode.upper()} | Generated by SSAA Financials Tool")
    instructions = [
        "",
        "How to use this workbook:",
        "1. Open each tab and fill / edit master data.",
        "2. Save the file when done.",
        "3. Upload back through the Client Dashboard → Master Data Upload (when available).",
        "4. For now, use this workbook as a working sheet — values can also be entered manually in the app.",
        "",
        "Sheets in this workbook:",
        " - Client Master  → Company info, registered office, auditor details",
        " - Directors      → DIN, designation, is_kmp flag, signs_financials flag",
        " - Shareholders   → Shareholding (CY/PY), promoter and director flags",
        " - Custom CoA     → Client-specific CoA codes (extension of standard 248 codes)",
        " - Policies       → Accounting policies at client level",
        "",
        "Notes:",
        " - Flags (is_kmp, signs_financials, is_promoter, is_director) accept: TRUE/FALSE, Yes/No, 1/0",
        " - Dates use ISO format YYYY-MM-DD",
        " - All amounts in INR",
        " - For BLANK template: a sample row may be included as guidance — replace with real data.",
        " - For EXPORT template: existing data is exported as-is.",
    ]
    for idx, text in enumerate(instructions, start=4):
        ws.cell(row=idx, column=1, value=text).font = Font(name="Calibri", size=10)
    ws.column_dimensions["A"].width = 100


def _build_client_master(wb, client=None, blank=True):
    ws = wb.create_sheet("Client Master")
    _add_title(ws, "Client Master Data",
               subtitle="One row per field — fill the Value column")

    headers = ["Field", "Value", "Notes"]
    _write_headers(ws, headers)

    fields = [
        ("Company Name", client.name if client else "ABC Private Limited", "Full legal name"),
        ("CIN", client.cin if client else "U12345MH2020PTC123456", "21-character corporate identification number"),
        ("PAN", client.pan if client else "ABCDE1234F", "Company PAN"),
        ("GSTIN", client.gstin if client else "27ABCDE1234F1Z5", "Primary GST number"),
        ("Date of Incorporation", client.date_of_incorporation.isoformat() if (client and client.date_of_incorporation) else "2020-04-01", "YYYY-MM-DD"),
        ("Registered Office", client.registered_office if client else "Mumbai, Maharashtra, India", "Full address"),
        ("Principal Activity", client.principal_activity if client else "Software development", "Main business"),
        ("Auditor Name", client.auditor_name if client else "ABC & Associates, Chartered Accountants", "Firm name"),
        ("Auditor FRN", client.auditor_frn if client else "001234N", "Firm registration number"),
        ("Auditor Membership No.", client.auditor_membership_no if client else "012345", "Partner's ICAI M. No."),
        ("Face Value per Share", client.face_value if client else 10, "₹ per equity share"),
        ("Authorised Shares (No.)", client.authorised_shares if client else 100000, "Total number"),
        ("Authorised Capital", client.authorised_capital if client else 1000000, "Auto = shares × face value"),
        ("Subscribed Shares (No.)", client.subscribed_shares if client else 50000, ""),
        ("Subscribed Capital", client.subscribed_capital if client else 500000, ""),
        ("Paid-up Shares (No.)", client.paidup_shares if client else 50000, ""),
        ("Paid-up Capital", client.paidup_capital if client else 500000, ""),
    ]
    _write_rows(ws, fields)
    _autosize(ws)


def _build_directors(wb, directors=None, blank=True):
    ws = wb.create_sheet("Directors")
    _add_title(ws, "Directors",
               subtitle="One row per director. Flags accept TRUE/FALSE or Yes/No.")

    headers = ["Name", "DIN", "Designation", "Date of Appointment",
               "PAN", "Is KMP", "Signs Financials", "Is Active"]
    _write_headers(ws, headers)

    rows = []
    if directors:
        for d in directors:
            rows.append([
                d.name,
                d.din or "",
                d.designation or "Director",
                d.date_of_appointment.isoformat() if d.date_of_appointment else "",
                d.pan or "",
                "TRUE" if d.is_kmp else "FALSE",
                "TRUE" if d.signs_financials else "FALSE",
                "TRUE" if d.is_active else "FALSE",
            ])
    if not rows:
        # Sample row for blank template
        rows.append([
            "Sample Director Name", "12345678", "Managing Director",
            "2020-04-01", "ABCPD1234E", "TRUE", "TRUE", "TRUE",
        ])
    _write_rows(ws, rows)
    _autosize(ws)


def _build_shareholders(wb, shareholders=None, blank=True):
    ws = wb.create_sheet("Shareholders")
    _add_title(ws, "Shareholders",
               subtitle="Include only those holding >5% or all promoters/directors.")

    headers = ["Name", "No. of Shares (CY)", "No. of Shares (PY)",
               "Face Value", "% Holding (CY)", "% Holding (PY)",
               "Is Promoter", "Is Director", "DIN", "PAN"]
    _write_headers(ws, headers)

    rows = []
    if shareholders:
        for s in shareholders:
            rows.append([
                s.name,
                s.no_of_shares_cy or 0,
                s.no_of_shares_py or 0,
                s.face_value or 10,
                s.pct_holding_cy or 0,
                s.pct_holding_py or 0,
                "TRUE" if s.is_promoter else "FALSE",
                "TRUE" if s.is_director else "FALSE",
                s.din or "",
                s.pan or "",
            ])
    if not rows:
        rows.append([
            "Sample Shareholder Pvt Ltd",
            30000, 30000, 10, 60.0, 60.0,
            "TRUE", "FALSE", "", "ABCDE1234F",
        ])
    _write_rows(ws, rows)
    _autosize(ws)


def _build_custom_coa(wb, codes=None, blank=True):
    ws = wb.create_sheet("Custom CoA")
    _add_title(ws, "Custom CoA Codes",
               subtitle="Client-specific extensions to the 248 standard codes.")

    headers = ["Code", "Particulars", "Parent Code",
               "Nature (Dr/Cr)", "FS Type (BS/PL)", "Note Ref"]
    _write_headers(ws, headers)

    rows = []
    if codes:
        for c in codes:
            rows.append([
                c.code, c.particulars,
                c.parent_code or "",
                c.nature or "",
                c.fs_type or "",
                c.note_ref or "",
            ])
    if not rows:
        rows.append([
            "BS-AS-02-06-99",
            "Custom: Sample Other Current Asset",
            "BS-AS-02-06", "Dr", "BS", "S",
        ])
    _write_rows(ws, rows)
    _autosize(ws)


def _build_policies(wb, policies=None, blank=True):
    ws = wb.create_sheet("Policies")
    _add_title(ws, "Accounting Policies (Client-level)",
               subtitle="One row per policy. Numbered sequence.")

    headers = ["Policy No.", "Title", "Body", "Is Active"]
    _write_headers(ws, headers)

    rows = []
    if policies:
        for p in policies:
            rows.append([
                p.policy_number,
                p.title,
                p.body,
                "TRUE" if p.is_active else "FALSE",
            ])
    if not rows:
        rows.append([
            1,
            "Basis of Preparation",
            ("The financial statements have been prepared in accordance with "
             "Indian Accounting Standards (Ind AS) prescribed under section 133 "
             "of the Companies Act, 2013, read with the Companies (Indian "
             "Accounting Standards) Rules, 2015."),
            "TRUE",
        ])
    _write_rows(ws, rows)
    ws.column_dimensions["A"].width = 12
    ws.column_dimensions["B"].width = 32
    ws.column_dimensions["C"].width = 80
    ws.column_dimensions["D"].width = 12


# ----- Public functions -----

def generate_blank_master_template() -> BytesIO:
    """Generate a blank master-data workbook with sample rows for guidance."""
    wb = Workbook()
    _build_readme(wb, client_name="(new client)", mode="blank")
    _build_client_master(wb, client=None, blank=True)
    _build_directors(wb, directors=None, blank=True)
    _build_shareholders(wb, shareholders=None, blank=True)
    _build_custom_coa(wb, codes=None, blank=True)
    _build_policies(wb, policies=None, blank=True)

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


def generate_current_master_template(db: Session, client_id: int) -> tuple[BytesIO, str]:
    """Generate a master-data workbook pre-filled with client's existing data."""
    client = db.query(Client).filter(Client.id == client_id).first()
    if not client:
        raise ValueError(f"Client {client_id} not found")

    directors = db.query(Director).filter(
        Director.client_id == client_id
    ).order_by(Director.id).all()
    shareholders = db.query(ClientShareholder).filter(
        ClientShareholder.client_id == client_id
    ).order_by(ClientShareholder.id).all()
    codes = db.query(CustomCoACode).filter(
        CustomCoACode.client_id == client_id
    ).order_by(CustomCoACode.code).all()
    policies = db.query(ClientPolicy).filter(
        ClientPolicy.client_id == client_id
    ).order_by(ClientPolicy.policy_number).all()

    wb = Workbook()
    _build_readme(wb, client_name=client.name, mode="export-current")
    _build_client_master(wb, client=client, blank=False)
    _build_directors(wb, directors=directors, blank=False)
    _build_shareholders(wb, shareholders=shareholders, blank=False)
    _build_custom_coa(wb, codes=codes, blank=False)
    _build_policies(wb, policies=policies, blank=False)

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    safe_name = "".join(c if c.isalnum() else "_" for c in (client.name or "client"))[:40]
    return buf, safe_name


def generate_ppe_template() -> BytesIO:
    """
    Standalone PPE schedule template pre-filled with standard asset-class CoA codes.
    User fills opening, additions, disposals, and depreciation columns.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "PPE Schedule"

    _add_title(ws, "Property, Plant & Equipment Schedule",
               subtitle="Pre-filled with standard asset-class codes. Fill amount columns.")

    headers = [
        "CoA Code", "Asset Class", "Tangible/Intangible",
        "Gross Opening (CY)", "Gross Additions (CY)", "Gross Disposals (CY)",
        "Dep Opening (CY)", "Dep for Year (CY)", "Dep on Disposals (CY)",
        "Gross Opening (PY)", "Gross Additions (PY)", "Gross Disposals (PY)",
        "Dep Opening (PY)", "Dep for Year (PY)", "Dep on Disposals (PY)",
    ]
    _write_headers(ws, headers)

    asset_classes = [
        ("BS-AS-01-01-01", "Land", "tangible"),
        ("BS-AS-01-01-02", "Buildings", "tangible"),
        ("BS-AS-01-01-03", "Plant and Equipment", "tangible"),
        ("BS-AS-01-01-04", "Furniture and Fixtures", "tangible"),
        ("BS-AS-01-01-05", "Vehicles", "tangible"),
        ("BS-AS-01-01-06", "Office Equipment", "tangible"),
        ("BS-AS-01-01-07", "Computers", "tangible"),
        ("BS-AS-01-01-08", "Leasehold Improvements", "tangible"),
        ("BS-AS-01-03-01", "Goodwill", "intangible"),
        ("BS-AS-01-03-02", "Brands / Trademarks", "intangible"),
        ("BS-AS-01-03-03", "Computer Software", "intangible"),
        ("BS-AS-01-03-04", "Patents", "intangible"),
        ("BS-AS-01-03-05", "Other Intangibles", "intangible"),
    ]
    rows = []
    for code, name, typ in asset_classes:
        rows.append([code, name, typ, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    _write_rows(ws, rows)
    _autosize(ws, min_width=10)

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
